version: '3.9'
services:
  # development
  boardso-web-dev:
    image: boardso-web-dev
    build:
      context: .
      dockerfile: ./apps/boardso/Dockerfile
      target: dev
    env_file:
      - ./apps/boardso/.env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
  # production
  boardso-web:
    image: boardso-web
    build:
      context: .
      dockerfile: ./apps/boardso/Dockerfile
      target: prod
    env_file:
      - ./apps/boardso/.env
    ports:
      - '3000:3000'
