version: '3.9'
services:
  # development
  boardso-web-dev:
    container_name: boardso-web-dev
    image: egofori/boardso-web-dev:1.0.0
    build:
      context: .
      dockerfile: ./apps/boardso/Dockerfile
      target: dev
    env_file:
      - ./apps/boardso/.env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
  # production
  boardso-web:
    container_name: boardso-web
    image: egofori/boardso-web:1.0.0
    build:
      context: .
      dockerfile: ./apps/boardso/Dockerfile
      target: prod
      args:
        NEXT_PUBLIC_API_BASE_URL: https://api.boardso.com
    env_file:
      - ./apps/boardso/.env
    ports:
      - '3000:3000'
